# Generated by Django 4.2.5 on 2024-01-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_face_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AlterField(
            model_name='product',
            name='cantFloor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='cantRoom',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
