# Generated by Django 4.2.5 on 2024-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_insale_remove_product_saleprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
