# Generated by Django 4.2.5 on 2024-01-16 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_architect_country_alter_architect_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
