# Generated by Django 4.2.5 on 2024-01-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_code_alter_product_cantfloor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inSale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salePrice',
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(default=1),
        ),
    ]
